on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: tarcanscloud/test-github-workflows/.github/actions/prepare.yml@main

  build:
    needs:
      - prepare
    runs-on: ubuntu-latest
    steps:
      - uses: tarcanscloud/test-github-workflows/.github/actions/build.yml@main

  test:
    needs:
      - prepare
    runs-on: ubuntu-latest
    steps:
      - uses: tarcanscloud/test-github-workflows/.github/actions/test.yml@main

  container-scan:
    needs:
      - prepare
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: tarcanscloud/test-github-workflows/.github/actions/container-scan.yml@main

  deploy:
    needs:
      - prepare
      - build
      - test
      - container-scan
    runs-on: ubuntu-latest
    steps:
      - uses: tarcanscloud/test-github-workflows/.github/actions/deploy.yml@main
